CREATE DATABASE GAMISH;

CREATE TABLE USUARIOS(
	ID SERIAL PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    SENHA VARCHAR(16) NOT NULL,
    EMAIL VARCHAR(50)
);

INSERT INTO USUARIOS(NOME, SENHA) VALUES('pimpozzo', '123456');
INSERT INTO USUARIOS(NOME, SENHA) VALUES('kekel', '123456');